//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RationBuilder.L10n {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RationBuilder.L10n.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очень высокая..
        /// </summary>
        internal static string DAILY_ACTIVITY_EXTREME {
            get {
                return ResourceManager.GetString("DAILY_ACTIVITY_EXTREME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Высокая..
        /// </summary>
        internal static string DAILY_ACTIVITY_HIGH {
            get {
                return ResourceManager.GetString("DAILY_ACTIVITY_HIGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слабая..
        /// </summary>
        internal static string DAILY_ACTIVITY_LIGHT {
            get {
                return ResourceManager.GetString("DAILY_ACTIVITY_LIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Средняя..
        /// </summary>
        internal static string DAILY_ACTIVITY_MEDIUM {
            get {
                return ResourceManager.GetString("DAILY_ACTIVITY_MEDIUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не установлено..
        /// </summary>
        internal static string DAILY_ACTIVITY_NONE {
            get {
                return ResourceManager.GetString("DAILY_ACTIVITY_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сидячая..
        /// </summary>
        internal static string DAILY_ACTIVITY_SIT {
            get {
                return ResourceManager.GetString("DAILY_ACTIVITY_SIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пятница.
        /// </summary>
        internal static string FRIDAY {
            get {
                return ResourceManager.GetString("FRIDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Женский..
        /// </summary>
        internal static string GENDER_FEMALE {
            get {
                return ResourceManager.GetString("GENDER_FEMALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мужской..
        /// </summary>
        internal static string GENDER_MALE {
            get {
                return ResourceManager.GetString("GENDER_MALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не установлен..
        /// </summary>
        internal static string HEIGHT_NONE {
            get {
                return ResourceManager.GetString("HEIGHT_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не правильный логин или пароль..
        /// </summary>
        internal static string LOG_ERROR {
            get {
                return ResourceManager.GetString("LOG_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Понедельник.
        /// </summary>
        internal static string MONDAY {
            get {
                return ResourceManager.GetString("MONDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Похудеть..
        /// </summary>
        internal static string PURPOSE_ACTIVITY_DOWN_WEIGHT {
            get {
                return ResourceManager.GetString("PURPOSE_ACTIVITY_DOWN_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нету..
        /// </summary>
        internal static string PURPOSE_ACTIVITY_NONE {
            get {
                return ResourceManager.GetString("PURPOSE_ACTIVITY_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поднять вес..
        /// </summary>
        internal static string PURPOSE_ACTIVITY_UP_WEIGHT {
            get {
                return ResourceManager.GetString("PURPOSE_ACTIVITY_UP_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не правильный возраст..
        /// </summary>
        internal static string REG_AGE_ERROR {
            get {
                return ResourceManager.GetString("REG_AGE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Такой логин уже занят..
        /// </summary>
        internal static string REG_LOG_BUSY_ERROR {
            get {
                return ResourceManager.GetString("REG_LOG_BUSY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не правильный логин..
        /// </summary>
        internal static string REG_LOG_ERROR {
            get {
                return ResourceManager.GetString("REG_LOG_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароли не совпадают..
        /// </summary>
        internal static string REG_PAS_A_ERROR {
            get {
                return ResourceManager.GetString("REG_PAS_A_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не правильный пароль..
        /// </summary>
        internal static string REG_PAS_ERROR {
            get {
                return ResourceManager.GetString("REG_PAS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Суббота.
        /// </summary>
        internal static string SATURDAY {
            get {
                return ResourceManager.GetString("SATURDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Воскресенье.
        /// </summary>
        internal static string SUNDAY {
            get {
                return ResourceManager.GetString("SUNDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Четверг.
        /// </summary>
        internal static string THURSDAY {
            get {
                return ResourceManager.GetString("THURSDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вторник.
        /// </summary>
        internal static string TUESDAY {
            get {
                return ResourceManager.GetString("TUESDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Среда.
        /// </summary>
        internal static string WEDNESDAY {
            get {
                return ResourceManager.GetString("WEDNESDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не установлен..
        /// </summary>
        internal static string WEIGHT_NONE {
            get {
                return ResourceManager.GetString("WEIGHT_NONE", resourceCulture);
            }
        }
    }
}
